# ---------- STEEP 1 (build) ----------
FROM node:22 as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---------- STEEP 2 (run) ----------
FROM node:22 as runner

WORKDIR /app

# Copy node_modules from builder (but you can also use npm ci --production)
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]
