services:
  nest:
    command: sh -c "npx drizzle-kit migrate && npm run start:prod"
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: postgres_prod
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata_prod:/data

volumes:
  pgdata_prod:
  redisdata_prod:
