services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      # - mongodb

  postgres:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - "6380:6379"
    volumes:
      - redisdata_dev:/data

  # mongodb:
  #   image: mongo:8
  #   container_name: mongo_dev
  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_USER: ${MONGO_USER}
  #     MONGO_PASS: ${MONGO_PASS}
  #   ports:
  #     - "27018:27017"
  #   volumes:
  #     - mongodata_dev:/data/db

volumes:
  pgdata_dev:
  redisdata_dev:
  # mongodata_dev:
