services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_prod
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: postgres_prod
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata_prod:/data

volumes:
  pgdata_prod:
  redisdata_prod:
