# ---------- ЕТАП 1 (build) ----------
FROM node:22 as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---------- ЕТАП 2 (run) ----------
FROM node:22 as runner

WORKDIR /app

# Копіюємо node_modules з builder (але можна використовувати npm ci --production)
COPY --from=builder /app/node_modules ./node_modules

# Копіюємо зібрані JS-файли
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]
